export const ENV = {
  SERVER_HOST: "https://pandorabackend-production.up.railway.app",
  API_URL: "https://pandorabackend-production.up.railway.app/api",
  ENDPOINTS: {
    AUTH: {
      LOGIN: "/auth/local",
    },
    USERS_ME: "/users/me",
    USERS: "/users",
    RESEARCH: "/researchs",
    PUBLICS: "/publics",
    SUBSCRIBERS: "/subscribers",
    INVESTIGATIONS: "/investigations",
    INVESTIGATION_TYPES: "/investigation-types",
    TEAMS: "/teams",
    RESEARCHERS: "/researchers",
    MATERIALS: "/materials",
    LOCATIONS: "/locations",
    PROJECTS: "/projects",
    COSTUMERS: "/costumers",
    EXPERIMENTS: "/experiments",
    VPS: "/vps",
    EXPERIMENT_TYPES: "/experiment-types",
    EXECUTION_METHODS: "/execution-methods",
  },
  TOKEN: "token",
};
